# .readthedocs.yaml
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

# Declare the Python requirements required to build the documentation
python:
   install:
   - requirements: requirements-dev.txt
